### ISSUE TITLE
Team Profile Generator

### ISSUE THREAD

**Issue by JaredMabus** [JaredMabus/team-builder-generator#1]
# User Story
A manager wants to generate a webpage that displays a team's basic info, to gain access to their emails and GitHub profiles

# Acceptance Criteria:
- [x] User is prompted for team members and their information
* Employee: name, id, email
 * Manager: name, id, email, room number
 * Engineer: name, id, email, and Github
 * Intern: name, id, email,  and school  
- [x] HTML file is generated, displaying a nicely formatted team roster
- [x] Email and GitHub links open to a new tab 

# Task:
- [x] Classes are created and have unit testing

# Design
![10-object-oriented-programming-homework-demo](https://user-images.githubusercontent.com/65479004/195186749-96d0008c-c86c-423e-b76c-e2a1284f46c4.png)
